# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6a064cb9a51407be025b635127f63148"
name = "click&collect"
handle = "click-collect-12"
application_url = "https://generally-decreased-cubic-geometry.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "saurabh-click-collect.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_locations,read_merchant_managed_fulfillment_orders,read_orders,read_product_listings,read_products,write_inventory,write_locations,write_products"

[auth]
redirect_urls = [
  "https://generally-decreased-cubic-geometry.trycloudflare.com/auth/callback",
  "https://generally-decreased-cubic-geometry.trycloudflare.com/auth/shopify/callback",
  "https://generally-decreased-cubic-geometry.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
