# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "82cd315401356aa6898b5b2349e495b8"
name = "saas-click-collect"
handle = "saas-click-collect"
application_url = "https://expired-glossary-bryan-elite.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "harshtestb2b.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,write_inventory,read_locales,read_locations,read_product_listings,read_products,read_script_tags,write_content,write_inventory,write_locations,write_products,write_script_tags"


[auth]
redirect_urls = [
  "https://expired-glossary-bryan-elite.trycloudflare.com/auth/callback",
  "https://expired-glossary-bryan-elite.trycloudflare.com/auth/shopify/callback",
  "https://expired-glossary-bryan-elite.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
