# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c2aef3cf60c016454d3da1bc06566b9e"
name = "clickncollect"
handle = "clickncollect-1"
application_url = "https://red-beauty-happy-dec.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "saas-click-collect.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://red-beauty-happy-dec.trycloudflare.com/auth/callback",
  "https://red-beauty-happy-dec.trycloudflare.com/auth/shopify/callback",
  "https://red-beauty-happy-dec.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
