# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ac9b99f068b4a8d49a05a3d2b3988c76"
name = "click-n-collect"
handle = "click-n-collect-6"
application_url = "https://tournaments-resistant-advancement-judy.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "saurabh-click-collect.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://tournaments-resistant-advancement-judy.trycloudflare.com/auth/callback",
  "https://tournaments-resistant-advancement-judy.trycloudflare.com/auth/shopify/callback",
  "https://tournaments-resistant-advancement-judy.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
