# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "60931bdf7285dee1caabff47cf07d01c"
name = "click&collect"
handle = "click-collect-11"
application_url = "https://idol-strength-zus-wine.trycloudflare.com"
embedded = true

[build]
dev_store_url = "recomendded-debras.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://idol-strength-zus-wine.trycloudflare.com/auth/callback",
  "https://idol-strength-zus-wine.trycloudflare.com/auth/shopify/callback",
  "https://idol-strength-zus-wine.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
