# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "16a66a5dc84be99f4814a92ca16805d6"
application_url = "https://out-reached-skin-throat.trycloudflare.com"
embedded = true
name = "vcc"
handle = "vcc-4"

[build]
include_config_on_deploy = true
dev_store_url = "saas-click-collect.myshopify.com"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_shipping,read_inventory,read_locales,read_locations,read_product_listings,read_products,read_publications,read_script_tags,write_content,write_inventory,write_locations,write_products,write_publications,write_script_tags"

[auth]
redirect_urls = [
  "https://out-reached-skin-throat.trycloudflare.com/auth/callback",
  "https://out-reached-skin-throat.trycloudflare.com/auth/shopify/callback",
  "https://out-reached-skin-throat.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
