# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "24effb1c40ba75cdb4e37b6533fe6a51"
name = "CnC-demo"
handle = "cnc-demo"
application_url = "https://fourth-basin-develop-dem.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "saas-click-collect.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_discounts,read_inventory,read_locales,read_locations,read_metaobjects,read_product_listings,read_products,read_script_tags,read_shipping,write_content,write_discounts,write_inventory,write_locales,write_locations,write_metaobjects,write_products,write_script_tags,write_shipping"

[auth]
redirect_urls = [
  "https://fourth-basin-develop-dem.trycloudflare.com/auth/callback",
  "https://fourth-basin-develop-dem.trycloudflare.com/auth/shopify/callback",
  "https://fourth-basin-develop-dem.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
